# Este es el Jupyter Notebook que se ha usado para hacer las prediciones de los models elegidos en el model_testing 

# Tambien se han aplicado aquí busqueda de modelos AutoML con H2o

In [ ]:
# %pip install h2o

In [ ]:
# %pip install auto-sklearn

In [ ]:
# %pip install xgboost

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split as tts
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error as mse
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor as RFR, GradientBoostingRegressor as GBR, AdaBoostRegressor, BaggingRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import BayesianRidge, ElasticNet
from sklearn.kernel_ridge import KernelRidge
from catboost import CatBoostRegressor as CBR

In [2]:
from sklearn.model_selection import GridSearchCV  
import xgboost as xgb
from xgboost import XGBRegressor
from scipy.optimize import minimize
from scipy.optimize import differential_evolution
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
from hyperopt import fmin, hp, tpe, Trials, space_eval, STATUS_OK
from lightgbm import LGBMRegressor as LGBMR
import h2o


from h2o.automl import H2OAutoML

# Importación de los archivos "límpios"

In [77]:

train = pd.read_csv("../data/train_clean4.csv")
test = pd.read_csv("../data/test_clean2.csv")

In [78]:
train.columns

Index(['log_price', 'room_type', 'cleaning_fee', 'cancellation_policy', 'city',
       'host_experience', 'accommodates', 'bathrooms', 'bedrooms',
       'property_type', 'mean_log_price', 'neighbourhood_cluster',
       'neighbourhood'],
      dtype='object')

In [79]:
train.head()

,log_price,room_type,cleaning_fee,cancellation_policy,city,host_experience,accommodates,bathrooms,bedrooms,property_type,mean_log_price,neighbourhood_cluster,neighbourhood
0,4.499810,Entire home/apt,1,flexible,NYC,poco_experimentado,2,1.0,1,Apartment,4.594133,5.0,Astoria
1,3.970292,Private room,1,strict,NYC,experimentado,2,1.0,1,Apartment,4.594133,4.0,Hamilton Heights
2,4.787492,Entire home/apt,1,moderate,NYC,muy_experimentado,4,1.0,1,Apartment,5.072061,4.0,Bedford-Stuyvesant
3,4.700480,Entire home/apt,0,moderate,NYC,muy_experimentado,3,1.1,1,Apartment,4.861277,6.0,Clinton Hill
4,5.192957,Entire home/apt,1,strict,NYC,muy_experimentado,3,1.0,1,Apartment,4.861277,6.0,Long Island City

# Selección de las columnas necesarias para el modelo

In [80]:
cols = ['log_price', 'room_type', 'city','bathrooms', 'bedrooms', 'mean_log_price', 'neighbourhood_cluster']

colst =['room_type', 'city','bathrooms', 'bedrooms', 'mean_log_price', 'neighbourhood_cluster']

train = train[cols]
test = test[colst]

In [81]:
train.head()

,log_price,room_type,city,bathrooms,bedrooms,mean_log_price,neighbourhood_cluster
0,4.499810,Entire home/apt,NYC,1.0,1,4.594133,5.0
1,3.970292,Private room,NYC,1.0,1,4.594133,4.0
2,4.787492,Entire home/apt,NYC,1.0,1,5.072061,4.0
3,4.700480,Entire home/apt,NYC,1.1,1,4.861277,6.0
4,5.192957,Entire home/apt,NYC,1.0,1,4.861277,6.0

# Empleo de AutoML con H2o

In [5]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
; Java HotSpot(TM) 64-Bit Server VM (build 25.391-b13, mixed mode)
  Starting server from C:\Users\daarr\anaconda3\Lib\site-packages\h2o\backend\bin\h2o.jar
  Ice root: C:\Users\daarr\AppData\Local\Temp\tmpxlc0e674
  JVM stdout: C:\Users\daarr\AppData\Local\Temp\tmpxlc0e674\h2o_daarr_started_from_python.out
  JVM stderr: C:\Users\daarr\AppData\Local\Temp\tmpxlc0e674\h2o_daarr_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       Europe/Paris
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.44.0.2
H2O_cluster_version_age:    19 days
H2O_cluster_name:           H2O_from_python_daarr_aotaov
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.475 Gb
H2O_cluster_total_cores:    0
H2O_cluster_allowed_cores:  0
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.11.4 final
--------------------------  -----------------------------

In [65]:
h2train = h2o.H2OFrame(train)

h2test = h2o.H2OFrame(test)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [66]:
y = 'log_price'

X = [c for c in h2train.columns if c != 'log_price']

In [67]:
# inicia auto-machine-learning


automl = H2OAutoML(max_models=100,        # nº de modelos
                   seed=42,              # random state
                   max_runtime_secs=600,
                   sort_metric='RMSE',stopping_metric = 'RMSE'
                  )

In [68]:
automl.train(x=X, y=y, training_frame=h2train)

AutoML progress: |
23:35:47.498: AutoML: XGBoost is not available; skipping it.

███████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OGradientBoostingEstimator : Gradient Boosting Machine
Model Key: GBM_grid_1_AutoML_7_20231127_233547_model_18


Model Summary:
    number_of_trees    number_of_internal_trees    model_size_in_bytes    min_depth    max_depth    mean_depth    min_leaves    max_leaves    mean_leaves
--  -----------------  --------------------------  ---------------------  -----------  -----------  ------------  ------------  ------------  -------------
    69                 69                          211280                 7            7            7             43            125           92.3188

ModelMetricsRegression: gbm
** Reported on train data. **

MSE: 0.1424963035117804
RMSE: 0.37748682561353103
MAE: 0.2739113553998313
RMSLE: 0.06459964900371586
Mean Residual Deviance: 0.1424963035117804

ModelMetricsRegression: gbm
** Reported on cross-validation data. **

MSE: 0.16544574911745638
RMSE: 0.4067502294006192
MAE: 0.2937274376166481
RMSLE: 0.06947081361497626
Mean Residual Deviance: 0.16544574911745638

Cross-Validation Metrics Summary:
                        mean       sd          cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
----------------------  ---------  ----------  ------------  ------------  ------------  ------------  ------------
mae                     0.293727   0.00174521  0.29178       0.293165      0.294755      0.296189      0.292748
mean_residual_deviance  0.165446   0.00516353  0.161076      0.161549      0.173904      0.165988      0.164712
mse                     0.165446   0.00516353  0.161076      0.161549      0.173904      0.165988      0.164712
r2                      0.680193   0.0101146   0.687048      0.685902      0.662936      0.679313      0.685767
residual_deviance       0.165446   0.00516353  0.161076      0.161549      0.173904      0.165988      0.164712
rmse                    0.406711   0.00630734  0.401343      0.401932      0.417018      0.407416      0.405848
rmsle                   0.0694615  0.00127611  0.0684063     0.068478      0.0714608     0.0699474     0.0690149

Scoring History:
    timestamp            duration          number_of_trees    training_rmse    training_mae    training_deviance
--  -------------------  ----------------  -----------------  ---------------  --------------  -------------------
    2023-11-27 23:43:00  2 min 35.987 sec  0                  0.719305         0.562737        0.517399
    2023-11-27 23:43:00  2 min 36.029 sec  5                  0.567193         0.435879        0.321708
    2023-11-27 23:43:01  2 min 36.085 sec  10                 0.48269          0.362909        0.232989
    2023-11-27 23:43:01  2 min 36.136 sec  15                 0.443513         0.329821        0.196704
    2023-11-27 23:43:01  2 min 36.184 sec  20                 0.419202         0.308918        0.175731
    2023-11-27 23:43:01  2 min 36.252 sec  25                 0.406            0.297598        0.164836
    2023-11-27 23:43:01  2 min 36.313 sec  30                 0.398667         0.291189        0.158935
    2023-11-27 23:43:01  2 min 36.366 sec  35                 0.393758         0.286891        0.155045
    2023-11-27 23:43:01  2 min 36.443 sec  40                 0.388793         0.282723        0.15116
    2023-11-27 23:43:01  2 min 36.496 sec  45                 0.386951         0.281267        0.149731
    2023-11-27 23:43:01  2 min 36.557 sec  50                 0.383922         0.278973        0.147396
    2023-11-27 23:43:01  2 min 36.613 sec  55                 0.381841         0.277265        0.145803
    2023-11-27 23:43:01  2 min 36.675 sec  60                 0.379738         0.275584        0.144201
    2023-11-27 23:43:01  2 min 36.720 sec  65                 0.378493         0.274678        0.143257
    2023-11-27 23:43:01  2 min 36.766 sec  69                 0.377487         0.273911        0.142496

Variable Importances:
variable               relative_importance    scaled_importance    percentage
---------------------  ---------------------  -------------------  ------------
room_type              36081                  1                    0.308422
mean_log_price         16479.3                0.45673              0.140866
neighbourhood          14641.9                0.405807             0.12516
neighbourhood_cluster  13226.7                0.366584             0.113063
accommodates           11837                  0.328066             0.101183
bathrooms              11159.9                0.3093               0.0953949
bedrooms               6802.8                 0.188542             0.0581505
city                   3352.85                0.0929256            0.0286603
property_type          1952.46                0.0541133            0.0166897
cancellation_policy    584.81                 0.0162082            0.00499897
cleaning_fee           470.622                0.0130435            0.00402289
host_experience        396.627                0.0109927            0.00339038

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [70]:
lider = automl.leaderboard

lider.head()

model_id                                          rmse       mse       mae      rmsle    mean_residual_deviance
--------------------------------------------  --------  --------  --------  ---------  ------------------------
GBM_grid_1_AutoML_7_20231127_233547_model_18  0.40675   0.165446  0.293727  0.0694708                  0.165446
GBM_grid_1_AutoML_7_20231127_233547_model_15  0.408649  0.166994  0.294866  0.0697961                  0.166994
GBM_grid_1_AutoML_7_20231127_233547_model_22  0.408897  0.167197  0.295101  0.0698669                  0.167197
GBM_grid_1_AutoML_7_20231127_233547_model_29  0.408978  0.167263  0.29579   0.0698766                  0.167263
GBM_grid_1_AutoML_7_20231127_233547_model_3   0.408997  0.167279  0.295313  0.069784                   0.167279
GBM_grid_1_AutoML_7_20231127_233547_model_13  0.40916   0.167412  0.294802  0.069858                   0.167412
GBM_grid_1_AutoML_7_20231127_233547_model_7   0.40917   0.16742   0.295762  0.0699086                  0.16742
GBM_grid_1_AutoML_7_20231127_233547_model_19  0.409713  0.167864  0.295948  0.0699799                  0.167864
GBM_grid_1_AutoML_7_20231127_233547_model_17  0.409966  0.168072  0.295555  0.0699157                  0.168072
GBM_grid_1_AutoML_7_20231127_233547_model_26  0.410123  0.168201  0.295165  0.0699843                  0.168201
[10 rows x 6 columns]

In [71]:
y_pred = automl.leader.predict(h2test)

gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

C:\Users\daarr\anaconda3\Lib\site-packages\h2o\job.py:81: UserWarning: Test/Validation dataset column 'neighbourhood' has levels not trained on: ["Chevy Chase, MD", "Government Center", "Graniteville", "New Dorp Beach", "Observatory Circle", "Suitland-Silver Hill, MD"]
  warnings.warn(w)

In [72]:
y_pred = y_pred.as_data_frame()

# Generación del documento de entrega

In [73]:
entrega3 = pd.read_csv("../data/muestra.csv")

In [74]:
entrega3["log_price"] = y_pred

In [75]:
entrega3.head(10)

   id  log_price
0   0   5.287376
1   1   5.212872
2   2   3.753726
3   3   4.911227
4   4   4.745525
5   5   5.337864
6   6   6.069925
7   7   4.194088
8   8   4.913758
9   9   5.191913

In [76]:
entrega3.to_csv("../data/entrega11.csv", index=False)

# Aplicación de otros modelos previamente testeados

In [ ]:


cols = ['property_type','log_price', 'room_type',
       'accommodates', 'bathrooms', 'cancellation_policy',
        'city','bedrooms', 'host_experience', 'neighbourhood_cluster', 'jacuzzi', 'fireplace', 
        'luxury', 'penthouse']

bnb2 = bnb2[cols]
bnb3 = bnb3[cols]

# One Hot Encoding

In [ ]:

bnb2 = pd.get_dummies(bnb2, columns=['cancellation_policy','room_type','city','host_experience','property_type'], drop_first=True)

bnb3 = pd.get_dummies(bnb3, columns=['cancellation_policy','room_type','city','host_experience','property_type'], drop_first=True)

# Separación del Dataframe en Train y Test

In [ ]:
X_train = bnb2.drop('log_price', axis=1)

y_train = bnb2.log_price

X_test = bnb3.drop('log_price', axis=1)

y_test= bnb3.log_price

In [ ]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

# Normalización

In [ ]:
escalador = StandardScaler()    # inicia el normalizador
 
escalador.fit(X_train[['accommodates', 'bathrooms','bedrooms']])   # ajusta segun train, saca media y std
 
X_train[['accommodates', 'bathrooms','bedrooms']] = escalador.fit_transform(X_train[['accommodates', 'bathrooms','bedrooms']])   # transforma train

In [ ]:
X_test[['accommodates', 'bathrooms','bedrooms']] = escalador.transform(X_test[['accommodates', 'bathrooms','bedrooms']])  # transforma test

In [ ]:
X_train.head()

In [ ]:
X_test.head()

# Entrenamiento de los modelos

In [ ]:
cbr = CBR( depth = 8, iterations= 500, learning_rate= 0.05)    # inicia el modelo


cbr.fit(X_train, y_train)   # entrena el modelo

In [ ]:
lgbmr = LGBMR(colsample_bytree=0.8, learning_rate=0.1, max_depth=5, n_estimators=200, subsample=0.8,force_row_wise=True, n_jobs=8)
lgbmr.fit(X_train, y_train)

In [ ]:
# rfr = RFR(max_depth= 10, n_estimators= 150)

# rfr.fit(X_train, y_train)

In [ ]:
# xgbr = XGBR(
#     objective='reg:squarederror',  # Puedes usar 'reg:squaredlogerror' para regresión logarítmica
#     max_depth=5,
#     learning_rate=0.1,
#     n_estimators=200
# )

# xgbr.fit(X_train, y_train)

In [ ]:
# mlp = MLPRegressor(activation= 'tanh', alpha= 0.0001, hidden_layer_sizes= (50,))

# mlp.fit(X_train, y_train)

In [ ]:
# gbr = GBR(learning_rate= 0.1, max_depth= 5, n_estimators= 150)    # inicia el modelo


# gbr.fit(X_train, y_train)   # entrena el modelo

# Predicción del modelo

In [ ]:
# y_pred1 = rfr.predict(X_test)
# y_pred2 = xgbr.predict(X_test)
# y_pred3 = mlp.predict(X_test)
# y_pred4 = gbr.predict(X_test)
y_pred5 = cbr.predict(X_test)
y_pred6 = lgbmr.predict(X_test)

# Generación del documento de entrega

In [ ]:
entrega3 = pd.read_csv("../data/muestra.csv")

In [69]:
entrega3["log_price"] = y_pred6

NameError: name 'y_pred6' is not defined

In [ ]:
entrega3.head(10)

In [ ]:
entrega3.to_csv("../data/entrega7.csv", index=False)